# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  #- /home/zealot/dotfiles/applications-config/test.rules
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

  # - job_name: cadvisor
  #   static_configs:
  #     - targets: ['localhost:8080']
  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 5s
  #   scrape_timeout: 5s

  - job_name: smartctl
    static_configs:
      - targets: ['localhost:9633']
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    scrape_timeout: 60s

  # - job_name: openvpn
  #   static_configs:
  #     - targets: ['localhost:9176']
  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 5s
  #   scrape_timeout: 5s

  - job_name: process
    static_configs:
      - targets: ['localhost:9256']
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    scrape_timeout: 10s

  # - job_name: vga
  #   static_configs:
  #     - targets: ['localhost:9445']
  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 10s
  #   scrape_timeout: 10s

  - job_name: postgres
    static_configs:
      - targets: ['localhost:9187']
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    scrape_timeout: 10s

  # - job_name: node-textfile
  #   static_configs:
  #     - targets: ['localhost:9101']
  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 2s
  #   scrape_timeout: 2s
  #   params:
  #     collect[]:
  #       - textfile
  #   metric_relabel_configs:
  #   - source_labels: [annotation_flux_weave_works_antecedent]
  #     regex: '(.*):(.*)/(.*)'
  #     replacement: '$1'
  #     target_label: namespace
  #   - source_labels: [annotation_flux_weave_works_antecedent]
  #     regex: '(.*):(.*)/(.*)'
  #     replacement: '$3'
  #     target_label: label_release
  #   - source_labels: [pod]
  #     regex: '(.*)-(.*)-(.*)'
  #     replacement: '$1'
  #     target_label: service
  #   - source_labels: [annotation_owner]
  #     action: replace
  #     regex: '(.*)'
  #     replacement: '$1'
  #     target_label: owner
  #   - source_labels: [__name__, service]
  #     action: replace
  #     regex: 'kong_http_status;.*\.(.*)\..*'
  #     replacement: '$1'
  #     target_label: deployment
  #   - source_labels: [__name__, service]
  #     action: replace
  #     regex: 'kong_latency_bucket;.*\.(.*)\..*'
  #     replacement: '$1'
  #     target_label: deployment

  # https://www.robustperception.io/life-of-a-label
